services:
  dots-ocr-vllm:
    build:
      context: .
      args:
        HUGGING_FACE_HUB_TOKEN: ${HF_TOKEN}
    container_name: dots-ocr-vllm
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      # no need running environment variables
    # environment:
    #   HUGGING_FACE_HUB_TOKEN: ${HF_TOKEN}
    #   VLLM_MODEL: ${VLLM_MODEL:-rednote-hilab/dots.ocr}
    #   VLLM_HOST: ${VLLM_HOST:-0.0.0.0}
    #   VLLM_PORT: ${VLLM_PORT:-8000}
    ipc: host
    # Request NVIDIA GPUs for local Compose (non‑Swarm)
    # device_requests:
    #   - driver: nvidia
    #     count: all
    #     capabilities: [ gpu ]
    restart: unless-stopped
    # Increase startup timeout for model download
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 300s  # 5 minutes for initial model download
